### ISSUE TITLE
Graph Analysis Script Argument Mismatch for function do_computations

### ISSUE THREAD

**Issue by codepujan** [riki95/Network-Robustness-with-NetworkX#1]
As per the instruction , I got the graph analysis script from 
[https://github.com/riki95/Bitcoin-Graph-study-with-NetworkX](url) and placed the required functions , `do_computations, create_graph, compute_centrality, plot_distribution` from the other script file . 
But , it seems that the arguments for the two  functions don't match .
Calling 
`        do_computations(g_remove_most_important, 'degree', 'degree')`

Recieving (from [https://github.com/riki95/Bitcoin-Graph-study-with-NetworkX](url) ) 
`def do_computations():`

  I tried totally ignoring the other argument other than the graph , but not sure if it'd give me the expected results.

**Comment by riki95** [comment]
Hello, it is an inconsistency due to my lack of update to this repo.
I just forgot to push an update on the first repo.

I've just pushed 2 hotfix to both repos and now they can interact.

By the way, in
`
do_computations(g_remove_most_important, 'degree', 'degree')
`
the first parameter is the graph itself, the second and third parameters are just labels to better print my files, so they are quite useless and can be avoided from you.

I've just removed them and now I think you are ready to go.
Let me know if you need more help

**Comment by frankg1** [comment]
i runned this script,but something wrong that said traceback FileNotFoundError: [Errno 2] No such file or directory: 'data/g1.png'    how can i solve this problem?thank you!

**Comment by riki95** [comment]
> i runned this script,but something wrong that said traceback FileNotFoundError: [Errno 2] No such file or directory: 'data/g1.png' how can i solve this problem?thank you!

First of all, please open a new issue.
Second, I can't see that piece of code in my script, it could be probably due to some modify you did.

**Comment by frankg1** [comment]
but i didnt do any modify,maybe i did something wrong with openning new issue, thank you !

2019-04-10 

gaoxiangxw 



发件人：Riccardo <notifications@github.com>
发送时间：2019-04-09 17:41
主题：Re: [riki95/Network-Robustness-with-NetworkX] Graph Analysis Script Argument Mismatch for function do_computations (#1)
收件人："riki95/Network-Robustness-with-NetworkX"<Network-Robustness-with-NetworkX@noreply.github.com>
抄送："frankg1"<gaoxiangxw@163.com>,"Comment"<comment@noreply.github.com>

i runned this script,but something wrong that said traceback FileNotFoundError: [Errno 2] No such file or directory: 'data/g1.png' how can i solve this problem?thank you!
First of all, please open a new issue.
Second, I can't see that piece of code in my script, it could be probably due to some modify you did.

**Comment by riki95** [comment]
> but i didnt do any modify,maybe i did something wrong with openning new issue, thank you ! 2019-04-10 gaoxiangxw 发件人：Riccardo <notifications@github.com> 发送时间：2019-04-09 17:41 主题：Re: [riki95/Network-Robustness-with-NetworkX] Graph Analysis Script Argument Mismatch for function do_computations (#1) 收件人："riki95/Network-Robustness-with-NetworkX"<Network-Robustness-with-NetworkX@noreply.github.com> 抄送："frankg1"<gaoxiangxw@163.com>,"Comment"<comment@noreply.github.com> i runned this script,but something wrong that said traceback FileNotFoundError: [Errno 2] No such file or directory: 'data/g1.png' how can i solve this problem?thank you! First of all, please open a new issue. Second, I can't see that piece of code in my script, it could be probably due to some modify you did. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Maybe you don't have the folder data.
Just create a data folder inside the repo and there you go.
